using System.Net;
using System.Net.Security;
using System.Net.Sockets;
using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Text.Json;
using Avalonia.Headless.XUnit;
using Avalonia.Threading;
using OmpGui.App;
using OmpGui.App.Services;
using OmpGui.App.ViewModels;
using OmpGui.ClientCore;

namespace OmpGui.Tests;

/// <summary>
/// The updater against a controlled release source: a real HTTPS server on the loopback interface (TLS with a test
/// certificate authority the client is told to trust, nothing disabled), serving update.json and a package the way a
/// published release would. Covers a newer version, no update, a server that is down or silent, a package with a wrong
/// checksum, a download cut off halfway, corrupted metadata, and that the installed app and the user's data are never
/// touched. With OMPGUI_UPDATE_DIST set to a folder written by tools/package/package.sh, the real update.json and
/// package of this platform are served instead of generated bytes.
/// </summary>
public sealed class UpdateServerTests
{
    private enum Behaviour { Serve, CutHalfway, Silent }

    private sealed record Route(byte[] Body, Behaviour Behaviour = Behaviour.Serve, int Status = 200);

    /// <summary>A minimal HTTP/1.1-over-TLS release server: one request per connection, routes by path.</summary>
    private sealed class ReleaseServer : IAsyncDisposable
    {
        private readonly TcpListener _listener = new(IPAddress.Loopback, 0);
        private readonly X509Certificate2 _cert;
        private readonly CancellationTokenSource _stop = new();
        private readonly Task _loop;
        public Dictionary<string, Route> Routes { get; } = [];
        public List<string> Requests { get; } = [];
        public int Port { get; }
        public string Url(string path) => $"https://127.0.0.1:{Port}/{path}";

        public ReleaseServer(X509Certificate2 cert)
        {
            _cert = cert;
            _listener.Start();
            Port = ((IPEndPoint)_listener.LocalEndpoint).Port;
            _loop = Task.Run(AcceptAsync);
        }

        private async Task AcceptAsync()
        {
            while (!_stop.IsCancellationRequested)
            {
                TcpClient client;
                try { client = await _listener.AcceptTcpClientAsync(_stop.Token); }
                catch (Exception) { return; }
                _ = Task.Run(() => HandleAsync(client));
            }
        }

        private async Task HandleAsync(TcpClient client)
        {
            using var _ = client;
            try
            {
                await using var tls = new SslStream(client.GetStream());
                await tls.AuthenticateAsServerAsync(new SslServerAuthenticationOptions { ServerCertificate = _cert }, _stop.Token);
                var head = new StringBuilder();
                var one = new byte[1];
                while (!head.ToString().EndsWith("\r\n\r\n", StringComparison.Ordinal) && await tls.ReadAsync(one, _stop.Token) == 1)
                    head.Append((char)one[0]);
                var path = head.ToString().Split(' ')[1].TrimStart('/');
                lock (Requests) Requests.Add(path);
                if (!Routes.TryGetValue(path, out var route))
                    route = new Route("not found"u8.ToArray(), Status: 404);
                if (route.Behaviour == Behaviour.Silent)
                {
                    await Task.Delay(Timeout.Infinite, _stop.Token);
                    return;
                }
                var reason = route.Status == 200 ? "OK" : "Not Found";
                await tls.WriteAsync(Encoding.ASCII.GetBytes(
                    $"HTTP/1.1 {route.Status} {reason}\r\nContent-Length: {route.Body.Length}\r\nContent-Type: application/octet-stream\r\nConnection: close\r\n\r\n"), _stop.Token);
                var send = route.Behaviour == Behaviour.CutHalfway ? route.Body.Length / 2 : route.Body.Length;
                await tls.WriteAsync(route.Body.AsMemory(0, send), _stop.Token);
                await tls.FlushAsync(_stop.Token);
                // CutHalfway: the connection closes here, short of the announced Content-Length.
            }
            catch (Exception) { }
        }

        public async ValueTask DisposeAsync()
        {
            await _stop.CancelAsync();
            _listener.Stop();
            try { await _loop; } catch (Exception) { }
        }
    }

    /// <summary>A test CA and a 127.0.0.1 / localhost server certificate it signed.</summary>
    private static (X509Certificate2 Ca, X509Certificate2 Server) Certificates()
    {
        // One clock reading: the server certificate must not outlive its CA, and two readings a second apart
        // made its notAfter later than the CA's (failed once in a one-core run).
        var now = DateTimeOffset.UtcNow;
        using var caKey = ECDsa.Create(ECCurve.NamedCurves.nistP256);
        var caReq = new CertificateRequest("CN=OMP GUI update test CA", caKey, HashAlgorithmName.SHA256);
        caReq.CertificateExtensions.Add(new X509BasicConstraintsExtension(true, false, 0, true));
        caReq.CertificateExtensions.Add(new X509KeyUsageExtension(X509KeyUsageFlags.KeyCertSign | X509KeyUsageFlags.CrlSign, true));
        using var ca = caReq.CreateSelfSigned(now.AddMinutes(-5), now.AddDays(2));

        using var key = ECDsa.Create(ECCurve.NamedCurves.nistP256);
        var req = new CertificateRequest("CN=127.0.0.1", key, HashAlgorithmName.SHA256);
        var san = new SubjectAlternativeNameBuilder();
        san.AddIpAddress(IPAddress.Loopback);
        san.AddDnsName("localhost");
        req.CertificateExtensions.Add(san.Build());
        req.CertificateExtensions.Add(new X509BasicConstraintsExtension(false, false, 0, false));
        req.CertificateExtensions.Add(new X509EnhancedKeyUsageExtension([new Oid("1.3.6.1.5.5.7.3.1")], false));
        using var signed = req.Create(ca, now.AddMinutes(-5), now.AddDays(1), RandomNumberGenerator.GetBytes(8));
        using var withKey = signed.CopyWithPrivateKey(key);
        // Through PKCS#12 so the private key is usable by SslStream on every OS.
        var server = X509CertificateLoader.LoadPkcs12(withKey.Export(X509ContentType.Pkcs12), null);
        return (X509CertificateLoader.LoadCertificate(ca.RawData), server);
    }

    /// <summary>A client that trusts exactly the test CA (full chain and host name validation stay on).</summary>
    private static HttpClient Client(X509Certificate2 ca) => new(new SocketsHttpHandler
    {
        SslOptions = new SslClientAuthenticationOptions
        {
            CertificateChainPolicy = new X509ChainPolicy
            {
                TrustMode = X509ChainTrustMode.CustomRootTrust,
                CustomTrustStore = { ca },
                RevocationMode = X509RevocationMode.NoCheck,
            },
        },
    }) { Timeout = TimeSpan.FromMinutes(30) }; // as the app's

    private sealed record Release(string Version, string Rid, string File, byte[] Package, string? Notes);

    /// <summary>The real packages of OMPGUI_UPDATE_DIST, or a generated one.</summary>
    private static Release TestRelease()
    {
        if (Environment.GetEnvironmentVariable("OMPGUI_UPDATE_DIST") is { Length: > 0 } dist)
        {
            using var doc = JsonDocument.Parse(File.ReadAllText(Path.Combine(dist, "update.json")));
            var version = doc.RootElement.GetProperty("version").GetString()!;
            var rid = UpdateChecker.ThisRid();
            var asset = doc.RootElement.GetProperty("assets").GetProperty(rid);
            var file = asset.GetProperty("file").GetString()!;
            var bytes = File.ReadAllBytes(Path.Combine(dist, file));
            Assert.Equal(asset.GetProperty("sha256").GetString(), Convert.ToHexStringLower(SHA256.HashData(bytes)));
            return new Release(version, rid, file, bytes, doc.RootElement.TryGetProperty("notes", out var n) ? n.GetString() : null);
        }
        var package = RandomNumberGenerator.GetBytes(3 << 20);
        return new Release("9.1.0", "linux-x64", "omp-gui-9.1.0-linux-x64.tar.gz", package, "Test release.");
    }

    private static byte[] Manifest(ReleaseServer server, Release r, string? sha = null) =>
        JsonSerializer.SerializeToUtf8Bytes(new
        {
            schema = 1,
            version = r.Version,
            notes = r.Notes,
            assets = new Dictionary<string, object>
            {
                [r.Rid] = new { file = r.File, url = server.Url(r.File), sha256 = sha ?? Convert.ToHexStringLower(SHA256.HashData(r.Package)), size = (long)r.Package.Length },
            },
        });

    /// <summary>update.json and its signature by the test release key.</summary>
    private static void Serve(ReleaseServer server, byte[] manifest)
    {
        server.Routes["update.json"] = new Route(manifest);
        server.Routes["update.json.sig"] = new Route(TestSigning.Sign(manifest));
    }

    /// <summary>An "installed app" and the user's data: their bytes must be the same after every scenario.</summary>
    private static (string Folder, Func<string> Fingerprint) InstallAndData()
    {
        var root = TestProcesses.TempDir("upd-installed");
        Directory.CreateDirectory(Path.Combine(root, "app"));
        File.WriteAllBytes(Path.Combine(root, "app", "OmpGui"), RandomNumberGenerator.GetBytes(4096));
        Directory.CreateDirectory(Path.Combine(root, "config", "OmpGui"));
        File.WriteAllText(Path.Combine(root, "config", "OmpGui", "omp-gui.local.json"), """{ "theme": "dark" }""");
        Directory.CreateDirectory(Path.Combine(root, ".omp", "agent", "sessions"));
        File.WriteAllText(Path.Combine(root, ".omp", "agent", "sessions", "s.jsonl"), """{"type":"session"}""");
        return (root, () => string.Join("\n", Directory.GetFiles(root, "*", SearchOption.AllDirectories).Order(StringComparer.Ordinal)
            .Select(f => Path.GetRelativePath(root, f) + " " + Convert.ToHexStringLower(SHA256.HashData(File.ReadAllBytes(f))))));
    }

    private static async Task Until(Func<bool> condition, string what, int seconds = 60)
    {
        var deadline = DateTime.UtcNow.AddSeconds(seconds);
        while (!condition())
        {
            if (DateTime.UtcNow > deadline) throw new TimeoutException("UI never reached: " + what);
            Dispatcher.UIThread.RunJobs();
            await Task.Delay(15);
        }
    }

    private static MainViewModel Settings(UpdateChecker checker, string downloads) =>
        new(new SessionController(TestProcesses.Fake("normal")), new AppArgs()) { Updates = checker, UpdateDownloadFolder = downloads };

    private static async Task<string> CheckAsync(MainViewModel vm)
    {
        vm.CheckForUpdatesCommand.Execute(null);
        await Until(() => !vm.IsUpdateBusy && vm.UpdateText != "Checking…", "check finished");
        return vm.UpdateText;
    }

    [AvaloniaFact]
    public async Task A_newer_release_is_offered_downloaded_and_verified_over_https()
    {
        var (ca, cert) = Certificates();
        await using var server = new ReleaseServer(cert);
        var r = TestRelease();
        Serve(server, Manifest(server, r));
        server.Routes[r.File] = new Route(r.Package);
        var (installed, fingerprint) = InstallAndData();
        var before = fingerprint();
        var downloads = Path.Combine(installed, "Downloads");
        var vm = Settings(new UpdateChecker(Client(ca), server.Url("update.json"), "0.0.1", r.Rid, TestSigning.PublicKey), downloads);

        Assert.StartsWith($"Version {r.Version} is available (you have 0.0.1).", await CheckAsync(vm));
        Assert.True(vm.UpdateAvailable);
        Assert.Equal(["update.json", "update.json.sig"], server.Requests); // the check downloads nothing else
        vm.DownloadUpdateCommand.Execute(null);
        await Until(() => !vm.IsUpdateBusy && vm.DownloadedUpdate is not null, "downloaded");
        Assert.StartsWith("Downloaded and verified", vm.UpdateText);
        Assert.Equal(Path.Combine(downloads, r.File), vm.DownloadedUpdate);
        Assert.Equal(r.Package, File.ReadAllBytes(vm.DownloadedUpdate!));
        Assert.Single(Directory.GetFiles(downloads)); // no .part left
        // Nothing installed or replaced: the app and the user's data are as before (the package only sits in Downloads).
        File.Delete(vm.DownloadedUpdate!);
        Directory.Delete(downloads);
        Assert.Equal(before, fingerprint());
        await vm.DisposeAsync();
    }

    [AvaloniaFact]
    public async Task The_same_version_is_up_to_date()
    {
        var (ca, cert) = Certificates();
        await using var server = new ReleaseServer(cert);
        var r = TestRelease();
        Serve(server, Manifest(server, r));
        var vm = Settings(new UpdateChecker(Client(ca), server.Url("update.json"), r.Version, r.Rid, TestSigning.PublicKey), TestProcesses.TempDir("upd-same"));
        Assert.Equal($"OMP GUI {r.Version} is up to date.", await CheckAsync(vm));
        Assert.False(vm.UpdateAvailable);
        await vm.DisposeAsync();
    }

    [AvaloniaFact]
    public async Task A_server_that_is_down_or_silent_is_reported_not_waited_for()
    {
        var (ca, cert) = Certificates();
        int port;
        await using (var gone = new ReleaseServer(cert)) port = gone.Port; // now nothing listens there
        var down = Settings(new UpdateChecker(Client(ca), $"https://127.0.0.1:{port}/update.json", "0.1.0", "linux-x64", TestSigning.PublicKey), TestProcesses.TempDir("upd-down"));
        Assert.StartsWith("Could not check for updates:", await CheckAsync(down));
        await down.DisposeAsync();

        await using var server = new ReleaseServer(cert);
        server.Routes["update.json"] = new Route([], Behaviour.Silent);
        var silent = Settings(new UpdateChecker(Client(ca), server.Url("update.json"), "0.1.0", "linux-x64", TestSigning.PublicKey) { StallTimeout = TimeSpan.FromSeconds(2) },
            TestProcesses.TempDir("upd-silent"));
        var started = DateTime.UtcNow;
        Assert.Equal("Could not check for updates: the update server did not answer within 2 s", await CheckAsync(silent));
        Assert.True(DateTime.UtcNow - started < TimeSpan.FromSeconds(30));
        await silent.DisposeAsync();

        // A feed address that is not published is an answer, not an error.
        var missing = Settings(new UpdateChecker(Client(ca), server.Url("nothing-here.json"), "0.1.0", "linux-x64", TestSigning.PublicKey), TestProcesses.TempDir("upd-404"));
        Assert.Equal("No release is published yet.", await CheckAsync(missing));
        await missing.DisposeAsync();
    }

    [AvaloniaFact]
    public async Task A_server_with_a_certificate_the_client_does_not_trust_is_refused()
    {
        var (_, cert) = Certificates();
        var (otherCa, _) = Certificates();
        await using var server = new ReleaseServer(cert);
        var r = TestRelease();
        Serve(server, Manifest(server, r));
        var vm = Settings(new UpdateChecker(Client(otherCa), server.Url("update.json"), "0.0.1", r.Rid, TestSigning.PublicKey), TestProcesses.TempDir("upd-untrusted"));
        Assert.StartsWith("Could not check for updates:", await CheckAsync(vm));
        Assert.False(vm.UpdateAvailable);
        await vm.DisposeAsync();
    }

    [AvaloniaFact]
    public async Task A_package_with_a_wrong_checksum_is_not_kept()
    {
        var (ca, cert) = Certificates();
        await using var server = new ReleaseServer(cert);
        var r = TestRelease();
        Serve(server, Manifest(server, r, sha: Convert.ToHexStringLower(SHA256.HashData("other"u8.ToArray()))));
        server.Routes[r.File] = new Route(r.Package);
        var downloads = TestProcesses.TempDir("upd-sha");
        var vm = Settings(new UpdateChecker(Client(ca), server.Url("update.json"), "0.0.1", r.Rid, TestSigning.PublicKey), downloads);
        await CheckAsync(vm);
        vm.DownloadUpdateCommand.Execute(null);
        await Until(() => !vm.IsUpdateBusy && vm.UpdateText.StartsWith("Download failed", StringComparison.Ordinal), "download refused");
        Assert.Contains("does not match the manifest", vm.UpdateText);
        Assert.Null(vm.DownloadedUpdate);
        Assert.Empty(Directory.GetFiles(downloads));
        await vm.DisposeAsync();
    }

    [AvaloniaFact]
    public async Task A_download_cut_off_halfway_leaves_nothing_and_can_be_retried()
    {
        var (ca, cert) = Certificates();
        await using var server = new ReleaseServer(cert);
        var r = TestRelease();
        Serve(server, Manifest(server, r));
        server.Routes[r.File] = new Route(r.Package, Behaviour.CutHalfway);
        var downloads = TestProcesses.TempDir("upd-cut");
        var vm = Settings(new UpdateChecker(Client(ca), server.Url("update.json"), "0.0.1", r.Rid, TestSigning.PublicKey), downloads);
        await CheckAsync(vm);
        vm.DownloadUpdateCommand.Execute(null);
        await Until(() => !vm.IsUpdateBusy && vm.UpdateText.StartsWith("Download failed", StringComparison.Ordinal), "download failed");
        Assert.Null(vm.DownloadedUpdate);
        Assert.Empty(Directory.GetFiles(downloads)); // no partial file, no .part

        // The server recovers: the same offer downloads completely.
        server.Routes[r.File] = new Route(r.Package);
        Assert.True(vm.DownloadUpdateCommand.CanExecute(null));
        vm.DownloadUpdateCommand.Execute(null);
        await Until(() => !vm.IsUpdateBusy && vm.DownloadedUpdate is not null, "retry downloaded");
        Assert.Equal(r.Package, File.ReadAllBytes(vm.DownloadedUpdate!));
        await vm.DisposeAsync();
    }

    [AvaloniaFact]
    public async Task A_download_that_stalls_fails_instead_of_hanging()
    {
        var (ca, cert) = Certificates();
        await using var server = new ReleaseServer(cert);
        var r = TestRelease();
        Serve(server, Manifest(server, r));
        server.Routes[r.File] = new Route([], Behaviour.Silent);
        var downloads = TestProcesses.TempDir("upd-stall");
        var vm = Settings(new UpdateChecker(Client(ca), server.Url("update.json"), "0.0.1", r.Rid, TestSigning.PublicKey) { StallTimeout = TimeSpan.FromSeconds(2) }, downloads);
        await CheckAsync(vm);
        vm.DownloadUpdateCommand.Execute(null);
        await Until(() => !vm.IsUpdateBusy && vm.UpdateText.StartsWith("Download failed", StringComparison.Ordinal), "stalled download failed", 30);
        Assert.Contains("sent nothing for 2 s", vm.UpdateText);
        Assert.Empty(Directory.GetFiles(downloads));
        await vm.DisposeAsync();
    }

    [AvaloniaTheory]
    [InlineData("{\"schema\":1,\"version\":\"9.1.0\",\"assets\":{\"linux-x64\":{\"file\":\"a.tar.gz\",")] // cut off
    [InlineData("<html>502 Bad Gateway</html>")]                                                            // not JSON
    [InlineData("{\"schema\":7,\"version\":\"9.1.0\",\"assets\":{}}")]                                       // unknown format
    [InlineData("{\"schema\":1,\"version\":\"9.1.0\",\"assets\":{\"linux-x64\":{\"file\":\"../../x\",\"url\":\"https://127.0.0.1/x\",\"sha256\":\"00\",\"size\":1}}}")]
    public async Task Corrupted_metadata_is_reported_and_offers_nothing(string manifest)
    {
        var (ca, cert) = Certificates();
        await using var server = new ReleaseServer(cert);
        Serve(server, Encoding.UTF8.GetBytes(manifest));
        var vm = Settings(new UpdateChecker(Client(ca), server.Url("update.json"), "0.1.0", "linux-x64", TestSigning.PublicKey), TestProcesses.TempDir("upd-corrupt"));
        Assert.StartsWith("Could not check for updates:", await CheckAsync(vm));
        Assert.False(vm.UpdateAvailable);
        Assert.False(vm.DownloadUpdateCommand.CanExecute(null));
        await vm.DisposeAsync();
    }
}
